language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

r_github_packages:
  - leifeld/xergm.common

notifications:
  email:
    recipients:
      - philip.leifeld@glasgow.ac.uk
    on_success: change
    on_failure: change
